#!/usr/bin/env bash

set -eux


function systemd_override () {
    DAEMON_SYSTEMD_PATH="/etc/systemd/system/snap.${PROJECT_NAME}.daemon.service.d"
    mkdir -p "${DAEMON_SYSTEMD_PATH}"

    script_log="${DAEMON_SYSTEMD_PATH}"/create-service.log
    exec 1>>$script_log
    exec 2>&1

    # We are copying the service conf file patch as editing the service file generated by snapd won't survive upgrades
    # copy set-limits.conf "${DAEMON_SYSTEMD_PATH}/override.conf"

    cp "${SNAP}"/etc/set-opensearch-limits.conf "${DAEMON_SYSTEMD_PATH}"/override.conf
}


function system_conf_override () {
    # 1. Set the number of open file handles
    ulimit -n 65535

    # 2. Allow the opensearch user to Disable all swap files:
    # TODO swapoff -a

    # 3. Ensuring sufficient virtual memory: https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
    # TODO sysctl -w vm.max_map_count=262144

    # 4. number of threads opensearch can create:
    # should be configured automatically if opensearch ran as a service

    # 5. Reduce TCP retransmission timeout = ~6 seconds
    # TODO sysctl -w net.ipv4.tcp_retries2=5
}


systemd_override
system_conf_override
