name: opensearch # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap

version: '2.2.0' # just for humans, typically '1.2+git' or '1.3.2'

summary: 'OpenSearch: community-driven, Apache 2.0-licensed search and analytics suite.'
description: |
    OpenSearch is a community-driven, Apache 2.0-licensed open source search and 
    analytics suite that makes it easy to ingest, search, visualize, and analyze data. 
    Developers build with OpenSearch for use cases such as application search, 
    log analytics, data observability, data ingestion, and more.

grade: devel # must be 'stable' to release into candidate/stable channels

confinement: devmode # use 'strict' once you have the right plugs and slots

assumes:
  - command-chain
  - snap-env
  - snapd2.56

system-usernames:
  snap_daemon: shared

plugs:
  systemd-write:
    interface: system-files
    write:
      - /etc/systemd/system

hooks:
  configure:
    plugs:
      - network
      - network-bind
      - systemd-write
    environment:
      PROJECT_NAME: ${SNAPCRAFT_PROJECT_NAME}
      PROJECT_VERSION: ${SNAPCRAFT_PROJECT_VERSION}

apps:
  # ----
  # Opensearch main service
  daemon:
    daemon: simple
    install-mode: disable
    command: wrappers/start.sh
    reload-command: wrappers/start.sh
    plugs:
      - network
      - network-bind
      - systemd-write
      - mount-observe
    environment:
      OPENSEARCH_HOME: ${SNAP_DATA}
      OPENSEARCH_JAVA_HOME: ${SNAP_DATA}/jdk
      OPENSEARCH_PATH_CONF: ${SNAP_COMMON}/config
      OPENSEARCH_TMPDIR: ${SNAP_COMMON}/tmp
      PROJECT_NAME: ${SNAPCRAFT_PROJECT_NAME}
      PROJECT_VERSION: ${SNAPCRAFT_PROJECT_VERSION}

  # ----
  # Plugins management
  plugins-add:
    command: wrappers/plugins/add.sh
    environment:
      OPENSEARCH_HOME: ${SNAP_DATA}
      PROJECT_NAME: ${SNAPCRAFT_PROJECT_NAME}

  plugins-list:
    command: wrappers/plugins/list.sh
    environment:
      OPENSEARCH_HOME: ${SNAP_DATA}
      PROJECT_NAME: ${SNAPCRAFT_PROJECT_NAME}

  plugins-remove:
    command: wrappers/plugins/remove.sh
    environment:
      OPENSEARCH_HOME: ${SNAP_DATA}
      PROJECT_NAME: ${SNAPCRAFT_PROJECT_NAME}

  # ----
  # Security basic management
  security-enable:
    command: ""

  security-disable:
    command: ""

  security-tls-certificates-on-leader-create:
    command: ""

  security-tls-certificates-on-leader-import:
    command: ""

  security-tls-certificates-on-node-create:
    command: ""

  security-tls-certificates-on-node-import:
    command: ""

  security-tls-certificates-load:
    command: ""

  security-tls-certificates-unload:
    command: ""

  security-rest-auth-basic-set:
    command: ""

  security-rest-auth-basic-unset:
    command: ""


parts:
  wrapper-scripts:
    plugin: dump
    source: ./wrappers
    source-type: local
    organize:
      start.sh: wrappers/start.sh

      plugins/add.sh: wrappers/plugins/add.sh
      plugins/list.sh: wrappers/plugins/list.sh
      plugins/remove.sh: wrappers/plugins/remove.sh

      security/enable.sh: wrappers/security/enable.sh
      security/disable.sh: wrappers/security/disable.sh
      security/tls.certificates.on-leader.create.sh: wrappers/security/tls.certificates.on-leader.create.sh
      security/tls.certificates.on-leader.import.sh: wrappers/security/tls.certificates.load.sh
      security/tls.certificates.unload.sh: wrappers/security/tls.certificates.unload.sh
      security/rest.auth.basic.set.sh: wrappers/security/rest.auth.basic.set.sh
      security/rest.auth.basic.unset.sh: wrappers/security/rest.auth.basic.set.sh

  wrapper-configs:
    plugin: dump
    source: snap/local
    organize:
      systemd/override.conf: etc/systemd/override.conf

  opensearch:
    plugin: dump
    source: https://opensearch-builds.s3.eu-west-1.amazonaws.com/core/opensearch-$SNAPCRAFT_PROJECT_VERSION-linux.tar.gz
    source-type: tar
    stage-packages:
      - util-linux
      - libfreetype6
      - libpng16-16
      - libxrender1
      - libx11-6
      - libxext6
      - libxi6
      - libxtst6
      - libpsm-infinipath1
      - libboost-all-dev
      - libasound2
