name: opensearch # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap

version: '2.1.0' # just for humans, typically '1.2+git' or '1.3.2'

summary: 'OpenSearch: community-driven, Apache 2.0-licensed search and analytics suite.'
description: |
    OpenSearch is a community-driven, Apache 2.0-licensed open source search and 
    analytics suite that makes it easy to ingest, search, visualize, and analyze data. 
    Developers build with OpenSearch for use cases such as application search, 
    log analytics, data observability, data ingestion, and more.

grade: devel # must be 'stable' to release into candidate/stable channels

confinement: devmode # use 'strict' once you have the right plugs and slots

# TODO: set: export ES_TMPDIR=/usr/share/elasticsearch/tmp

system-usernames:
  opensearch: shared

apps:
  daemon:
    daemon: simple
    command-chain:
      - bin/systemd/create-service.sh
    command: bin/start.sh
    reload-command: bin/opensearch

parts:
  opensearch:
    plugin: dump
    source: https://opensearch-builds.s3.eu-west-1.amazonaws.com/core/opensearch-min-$SNAPCRAFT_PROJECT_VERSION-linux-x64.tar.gz
    source-type: tar
    override-build: |
      snapcraftctl build
      bin/install.sh
    stage-packages:
      - libfreetype6
      - libpng16-16
      - libxrender1
      - libx11-6
      - libxext6
      - libxi6
      - libboost-all-dev
      - libasound2
      - util-linux
