name: Build OpenSearch from source and run tests

env:
  VERSION: 2.2.0
  RELEASE: edge

on:
  push:
    branches:
      - edge

jobs:
  build:
    name: Build Snap
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: edge

      - id: build-snap
        name: Build snap
        uses: snapcore/action-build@v1

      - name: Upload built snap job artifact
        uses: actions/upload-artifact@v3
        with:
          name: opensearch_snap_amd64
          path: opensearch_${{env.VERSION}}_amd64.snap

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: edge

      - name: Download snap file
        uses: actions/download-artifact@v3
        with:
          name: opensearch_snap_amd64
          path: ./

      - name: Publish snap to Store
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_CREDENTIALS_KEY: ${{ secrets.STORE_LOGIN }}
        with:
          snap: opensearch_${{env.VERSION}}_amd64.snap
          release: ${{env.RELEASE}}
