name: Build OpenSearch from source and run tests

env:
  VERSION: 2.2.0
  RELEASE: edge

on:
  push:
    branches:
      - edge

jobs:
  build:
    name: Build Snap
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: edge

      - id: build-snap
        name: Build snap
        uses: snapcore/action-build@v1

      - name: Upload built snap job artifact
        uses: actions/upload-artifact@v3
        with:
          name: opensearch_snap_amd64
          path: opensearch_${{env.VERSION}}_amd64.snap

  test:
    name: Test Snap
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download snap file
        uses: actions/download-artifact@v3
        with:
          name: opensearch_snap_amd64
          path: ./

      - name: Install snap file
        run: |
          sudo snap install opensearch_${{env.VERSION}}_amd64.snap --dangerous
          sudo snap connect opensearch:systemd-write

          sudo snap restart opensearch.daemon
          sleep 30s
          curl -XGET http://localhost:9200 
          
          sudo snap run opensearch.setup \
              --node-name cluster-manager-0 \
              --tls-init-setup yes \
              --tls-root-password root1234 \
              --tls-admin-password admin1234 \
              --tls-node-password node1234 \
              --node-roles cluster_manager,data
          
          sudo snap restart opensearch.daemon \
              --init-security yes \
              --admin-password admin1234
          sleep 30s
          curl -XGET http://localhost:9200   # ERROR
          curl -XGET https://localhost:9200
          

        with:
          name: opensearch_snap_amd64
          path: ./


  publish:
    name: publish
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: edge

      - name: Download snap file
        uses: actions/download-artifact@v3
        with:
          name: opensearch_snap_amd64
          path: ./

      - name: Publish snap to Store
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_CREDENTIALS_KEY: ${{ secrets.STORE_LOGIN }}
        with:
          snap: opensearch_${{env.VERSION}}_amd64.snap
          release: ${{env.RELEASE}}
